### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by FReichelt** [aauren/rtorrent-exporter#2]
Hello,
thank you very much for maintaining this version of the rtorrent-exporter, it's a great addition to my setup. Since I'm not really a big user of grafana, it has been a struggle creating a nice looking dashboard. I've managed to do so, but I believe many users feel the same, therefore it would be great if you could share your config.

Thank you very much in advance :)

**Comment by aauren** [comment]
I'm not sure that I am exactly the best dashboard-er out there, but I added an example here: https://github.com/aauren/rtorrent-exporter/blob/master/resources/grafana-dashboard.json

I've also tried uploading it to grafana.com: https://grafana.com/grafana/dashboards/22581 however, my experience is that it can take several weeks to get them to actually show it.
